spring.application.name=taskflowv3

spring.profiles.active=DEV

jwt.secret=56wbzjO4rg7jqhfEuU4ZCRN+q4Heo2yaGNmSI7Ms69g=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Turn Statistics on
logging.level.org.hibernate.stat=debug
logging.level.org.hibernate.type=trace

# Logger configuration
# Log file name (relative path to the current directory or an absolute path)
logging.file.name=C:/Users/chakr/logs/app.log
# The logging level for the root logger (can be TRACE, DEBUG, INFO, WARN, ERROR)
logging.level.root=INFO
# Pattern for the log entries (optional)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
# Limit the size of each log file (optional)
logging.file.max-size=10MB
# Keep a certain number of archived log files (optional)
logging.file.max-history=30
# Specify whether to roll over logs when the application restarts (optional)
logging.file.total-size-cap=100MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jayanta4u2006@gmail.com
spring.mail.password=uiev mwbm iper qvhb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true